name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Construção da imagem Docker
      - uses: docker/build-push-action@v6.15.0
        with: 
          context: ./app
          file: ./src/Dockerfile
          push: true
          tags: | 
            isaleite05/lacrei-app:v2
            isaleite05/lacrei-app:latest

            
