name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
       
      
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v6.15.0
        with: 
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: | 
            isaleite05/lacrei-app:v2
            isaleite05/lacrei-app:latest
